receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  # Add other exporters like elasticsearch, prometheus, etc.

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug] 